# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ruta_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailId', models.CharField(max_length=100)),
                ('originStationName', models.CharField(max_length=100)),
                ('destinationStationName', models.CharField(max_length=100)),
                ('transportType', models.CharField(max_length=100)),
                ('maxTariff', models.CharField(max_length=100)),
                ('photoUrl', models.URLField()),
                ('notes', models.TextField()),
                ('totalMinutes', models.IntegerField()),
                ('totalMeters', models.IntegerField()),
                ('gtfsStatus', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='punto',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='main.Ruta'),
        ),
    ]
