# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='photoUrl',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='totalMeters',
            field=models.FloatField(),
        ),
    ]
