# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160306_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='primerPunto',
            new_name='primerPuntolat',
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='ultimoPunto',
            new_name='primerPuntolon',
        ),
        migrations.AddField(
            model_name='ruta',
            name='ultimoPuntolat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ultimoPuntolon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
